### ISSUE TITLE
Dynamic require of "@softarc/native-federation-runtime" is not supported

### ISSUE THREAD

**Issue by lifeng1992** [manfredsteyer/native-federation-core-microfrontend#2]
```
chunk-EFBCFLQ4.js:12 Uncaught Error: Dynamic require of "@softarc/native-federation-runtime" is not supported
    at chunk-EFBCFLQ4.js:12:9
    at node_modules/@softarc/native-federation/src/index.js (main.js:373:26)
    at __require2 (chunk-EFBCFLQ4.js:18:50)
    at mfe1/main.ts (main.js:380:44)
    at __require2 (chunk-EFBCFLQ4.js:18:50)
    at main.js:387:16
```

**Comment by lifeng1992** [comment]
sorry, my mistake
